spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample_db?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: password
    driverClassName: com.mysql.jdbc.Driver
  batch:
    initialize-schema: always
